# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-04 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='upated',
            new_name='updated',
        ),
    ]
