# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_auto_20191104_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='kategory',
            new_name='kategori',
        ),
    ]
